packages:
  - packages/*

catalog:
  '@intlify/utils': ^1.0.1
  '@types/node': ^24.10.0
  publint: ^0.3.15
  tsdown: ^0.16.4
  typedoc: ^0.28.14
  typedoc-plugin-markdown: ^4.9.0
  typescript: ^5.9.3
  srvx: ^0.9.6

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - eslint-plugin-jsdoc

onlyBuiltDependencies:
  - deno
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
