packages:
  - packages/*

catalog:
  '@types/node': ^24.10.0
  unbuild: ^3.6.1

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - eslint-plugin-jsdoc

onlyBuiltDependencies:
  - deno
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
