packages:
  - packages/*

catalog:
  '@types/node': ^24.10.0
  unbuild: ^3.6.1
  typedoc: ^0.28.14
  typedoc-plugin-markdown: ^4.9.0
  typescript: ^5.9.3

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - eslint-plugin-jsdoc

onlyBuiltDependencies:
  - deno
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
