packages:
  - packages/*

catalog:
  '@intlify/utils': ^1.0.1
  '@intlify/core': ^11.3.0
  '@types/node': ^25.5.2
  publint: ^0.3.18
  tsdown: ^0.21.7
  typedoc: ^0.28.18
  typedoc-plugin-markdown: ^4.11.0
  typescript: ^6.0.2
  srvx: ^0.11.15

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - deno
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
  - '@oxfmt/**'
  - oxfmt
