name: Typos
on:
  pull_request:
    branches-ignore:
      - gh-pages
      - releases/**
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Spell check
        uses: crate-ci/typos@0c17dabcee8b8f1957fa917d17393a23e02e1583 # v1.36.3
